/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: moyicat (https://sketchfab.com/moyicat)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/room-07-magicavoxel-59d7f7e9c72840138e1fe0413c6017a6
title: Room 07 / MagicaVoxel
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh
  }
  materials: {
    palette: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/room7-transformed.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2.31} userData={{ name: 'Sketchfab_model' }}>
        <group name="room_07objcleanermaterialmergergles" position={[-32, -32, 0]} userData={{ name: 'room_07.obj.cleaner.materialmerger.gles' }}>
          <group name="Object_2" userData={{ name: 'Object_2' }}>
            <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.palette} userData={{ name: 'Object_3' }} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room7-transformed.glb')
