/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: moyicat (https://sketchfab.com/moyicat)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/room-12-blender-370c896a973244888337b0f8e5263fb7
title: Room 12 / Blender
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    HighFloor_0: THREE.Mesh
    Cushion_0: THREE.Mesh
    ShelfWall_0: THREE.Mesh
    Bowl_03_0: THREE.Mesh
    Bowl_03_1: THREE.Mesh
    Bowl_02_0: THREE.Mesh
    Bowl_02_1: THREE.Mesh
    Bowl_02_2: THREE.Mesh
    Bowl_01_0: THREE.Mesh
    Bowl_01_1: THREE.Mesh
    ShelfVase_0: THREE.Mesh
    TopShelf_0: THREE.Mesh
    TopShelf_1: THREE.Mesh
    BottomShelf_0: THREE.Mesh
    BottomShelf_1: THREE.Mesh
    Lamp_0: THREE.Mesh
    Lamp_1: THREE.Mesh
    ChairFar_0: THREE.Mesh
    ChairFar_1: THREE.Mesh
    ChairFar_0_1: THREE.Mesh
    ChairFar_1_1: THREE.Mesh
    TableVase_0: THREE.Mesh
    TeaBase_0: THREE.Mesh
    TeaBaseFeet_0: THREE.Mesh
    TeaPotHandle_0: THREE.Mesh
    TeaPotBody_0: THREE.Mesh
    Plate_0: THREE.Mesh
    TeaPotBody001_0: THREE.Mesh
    TeaPotHandle001_0: THREE.Mesh
    TableStand_0: THREE.Mesh
    TableTop_0: THREE.Mesh
    Windows_0: THREE.Mesh
    Windows_1: THREE.Mesh
    WallLeft_0: THREE.Mesh
    WallLeft_1: THREE.Mesh
    LowCeil_0: THREE.Mesh
    WallRight_0: THREE.Mesh
    WallRight_1: THREE.Mesh
    Floor_0: THREE.Mesh
    Floor_1: THREE.Mesh
    Floor_2: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    CushionBrown: THREE.MeshStandardMaterial
    TatamiGreen: THREE.MeshStandardMaterial
    CupInnerRed: THREE.MeshStandardMaterial
    CupOuterPurple: THREE.MeshStandardMaterial
    CupOuterBeige: THREE.MeshStandardMaterial
    CupOuterPink: THREE.MeshStandardMaterial
    CupInnerPurple: THREE.MeshStandardMaterial
    CupOuterGold: THREE.MeshStandardMaterial
    TeaPotWhite: THREE.MeshStandardMaterial
    ShelfTopDark: THREE.MeshStandardMaterial
    Lamp: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    TableVaseGray: THREE.MeshStandardMaterial
    DarkerWood: THREE.MeshStandardMaterial
    WoodDark: THREE.MeshStandardMaterial
    WindowWhite: THREE.MeshStandardMaterial
    WallLight: THREE.MeshStandardMaterial
    FloorWhite: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/room12-transformed.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={139.95} userData={{ name: 'Sketchfab_model' }}>
        <group name="Root" userData={{ name: 'Root' }}>
          <group name="Lights" userData={{ name: 'Lights' }}>
            <group name="Sun" position={[10.08, 2.7, 13.45]} rotation={[-0.28, 0.7, 2.32]} scale={[1, 0.98, 0.96]} userData={{ name: 'Sun' }} />
            <group name="Hemi" position={[10.08, 8.82, 9.9]} rotation={[-0.27, 0.6, 1.93]} userData={{ name: 'Hemi' }} />
          </group>
          <group name="Objects" userData={{ name: 'Objects' }}>
            <group name="LiftedBase" userData={{ name: 'LiftedBase' }}>
              <group name="HighFloor" position={[-2, 0, 1]} userData={{ name: 'HighFloor' }}>
                <mesh name="HighFloor_0" geometry={nodes.HighFloor_0.geometry} material={materials.Wood} userData={{ name: 'HighFloor_0' }} />
              </group>
              <group name="Cushion" position={[-2, 0, 1]} scale={[0.4, 0.4, 0.5]} userData={{ name: 'Cushion' }}>
                <mesh name="Cushion_0" geometry={nodes.Cushion_0.geometry} material={materials.CushionBrown} userData={{ name: 'Cushion_0' }} />
              </group>
            </group>
            <group name="Shelf_Group" userData={{ name: 'Shelf Group' }}>
              <group name="ShelfWall" position={[-3, 1, 0]} userData={{ name: 'ShelfWall' }}>
                <mesh name="ShelfWall_0" geometry={nodes.ShelfWall_0.geometry} material={materials.TatamiGreen} userData={{ name: 'ShelfWall_0' }} />
              </group>
              <group name="Bowl_03" position={[-3.5, -1.5, 2]} scale={[0.34, 0.34, 0.28]} userData={{ name: 'Bowl 03' }}>
                <mesh name="Bowl_03_0" geometry={nodes.Bowl_03_0.geometry} material={materials.CupInnerRed} userData={{ name: 'Bowl 03_0' }} />
                <mesh name="Bowl_03_1" geometry={nodes.Bowl_03_1.geometry} material={materials.CupOuterPurple} userData={{ name: 'Bowl 03_1' }} />
              </group>
              <group name="Bowl_02" position={[-3.5, -2, 2]} scale={[0.4, 0.4, 0.42]} userData={{ name: 'Bowl 02' }}>
                <mesh name="Bowl_02_0" geometry={nodes.Bowl_02_0.geometry} material={materials.CupInnerRed} userData={{ name: 'Bowl 02_0' }} />
                <mesh name="Bowl_02_1" geometry={nodes.Bowl_02_1.geometry} material={materials.CupOuterBeige} userData={{ name: 'Bowl 02_1' }} />
                <mesh name="Bowl_02_2" geometry={nodes.Bowl_02_2.geometry} material={materials.CupOuterPink} userData={{ name: 'Bowl 02_2' }} />
              </group>
              <group name="Bowl_01" position={[-3.5, -2.5, 2]} scale={0.3} userData={{ name: 'Bowl 01' }}>
                <mesh name="Bowl_01_0" geometry={nodes.Bowl_01_0.geometry} material={materials.CupInnerPurple} userData={{ name: 'Bowl 01_0' }} />
                <mesh name="Bowl_01_1" geometry={nodes.Bowl_01_1.geometry} material={materials.CupOuterGold} userData={{ name: 'Bowl 01_1' }} />
              </group>
              <group name="ShelfVase" position={[-3.5, -3.5, 2]} scale={0.3} userData={{ name: 'ShelfVase' }}>
                <mesh name="ShelfVase_0" geometry={nodes.ShelfVase_0.geometry} material={materials.TeaPotWhite} userData={{ name: 'ShelfVase_0' }} />
              </group>
              <group name="Shelf" userData={{ name: 'Shelf' }}>
                <group name="TopShelf" position={[-3, -3, 4.5]} userData={{ name: 'TopShelf' }}>
                  <mesh name="TopShelf_0" geometry={nodes.TopShelf_0.geometry} material={materials.TatamiGreen} userData={{ name: 'TopShelf_0' }} />
                  <mesh name="TopShelf_1" geometry={nodes.TopShelf_1.geometry} material={materials.Wood} userData={{ name: 'TopShelf_1' }} />
                </group>
                <group name="BottomShelf" position={[-3, -3, 1]} userData={{ name: 'BottomShelf' }}>
                  <mesh name="BottomShelf_0" geometry={nodes.BottomShelf_0.geometry} material={materials.TatamiGreen} userData={{ name: 'BottomShelf_0' }} />
                  <mesh name="BottomShelf_1" geometry={nodes.BottomShelf_1.geometry} material={materials.ShelfTopDark} userData={{ name: 'BottomShelf_1' }} />
                </group>
              </group>
            </group>
            <group name="Lamp" position={[-0.2, 0, 7.5]} scale={0.5} userData={{ name: 'Lamp' }}>
              <mesh name="Lamp_0" geometry={nodes.Lamp_0.geometry} material={materials.Lamp} userData={{ name: 'Lamp_0' }} />
              <mesh name="Lamp_1" geometry={nodes.Lamp_1.geometry} material={materials.Black} userData={{ name: 'Lamp_1' }} />
            </group>
            <group name="Chairs" userData={{ name: 'Chairs' }}>
              <group name="ChairFar" position={[2, -1, 0]} scale={0.75} userData={{ name: 'ChairFar' }}>
                <mesh name="ChairFar_0" geometry={nodes.ChairFar_0.geometry} material={materials.Wood} userData={{ name: 'ChairFar_0' }} />
                <mesh name="ChairFar_1" geometry={nodes.ChairFar_1.geometry} material={materials.Black} userData={{ name: 'ChairFar_1' }} />
              </group>
              <group name="ChairNear" position={[2, 1, 0]} scale={0.75} userData={{ name: 'ChairNear' }}>
                <mesh name="ChairFar_0_1" geometry={nodes.ChairFar_0_1.geometry} material={materials.Wood} userData={{ name: 'ChairFar_0' }} />
                <mesh name="ChairFar_1_1" geometry={nodes.ChairFar_1_1.geometry} material={materials.Black} userData={{ name: 'ChairFar_1' }} />
              </group>
            </group>
            <group name="Table" userData={{ name: 'Table' }}>
              <group name="TableVase" position={[-1.45, -0.03, 2]} scale={0.48} userData={{ name: 'TableVase' }}>
                <mesh name="TableVase_0" geometry={nodes.TableVase_0.geometry} material={materials.TableVaseGray} userData={{ name: 'TableVase_0' }} />
              </group>
              <group name="CenterTea" userData={{ name: 'CenterTea' }}>
                <group name="TeaBase" position={[0.06, 0.71, 2]} scale={0.5} userData={{ name: 'TeaBase' }}>
                  <mesh name="TeaBase_0" geometry={nodes.TeaBase_0.geometry} material={materials.Black} userData={{ name: 'TeaBase_0' }} />
                </group>
                <group name="TeaBaseFeet" position={[0.06, 0.71, 2.3]} rotation={[0, 0, 0.52]} scale={0.04} userData={{ name: 'TeaBaseFeet' }}>
                  <mesh name="TeaBaseFeet_0" geometry={nodes.TeaBaseFeet_0.geometry} material={materials.Black} userData={{ name: 'TeaBaseFeet_0' }} />
                </group>
                <group name="TeaPot" position={[0.09, 0, 2.35]} scale={0.5} userData={{ name: 'TeaPot' }}>
                  <group name="TeaPotHandle" position={[-0.02, 1.42, 0.85]} rotation={[-Math.PI / 2, -Math.PI / 8, Math.PI / 2]} userData={{ name: 'TeaPotHandle' }}>
                    <mesh name="TeaPotHandle_0" geometry={nodes.TeaPotHandle_0.geometry} material={materials.Black} userData={{ name: 'TeaPotHandle_0' }} />
                  </group>
                  <group name="TeaPotBody" position={[-0.02, 1.42, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.5, 0.5, 0.38]} userData={{ name: 'TeaPotBody' }}>
                    <mesh name="TeaPotBody_0" geometry={nodes.TeaPotBody_0.geometry} material={materials.Black} userData={{ name: 'TeaPotBody_0' }} />
                  </group>
                </group>
              </group>
              <group name="TablePlate" userData={{ name: 'TablePlate' }}>
                <group name="Plate" position={[-0.72, -1.04, 2]} scale={0.45} userData={{ name: 'Plate' }}>
                  <mesh name="Plate_0" geometry={nodes.Plate_0.geometry} material={materials.DarkerWood} userData={{ name: 'Plate_0' }} />
                </group>
                <group name="TeaPotinPlate" position={[-1.15, -1.08, 2.04]} rotation={[0, 0, Math.PI / 2]} scale={[0.3, 0.3, 0.38]} userData={{ name: 'TeaPotinPlate' }}>
                  <group name="TeaPotBody001" position={[0.19, -1.26, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.5, 0.5, 0.38]} userData={{ name: 'TeaPotBody.001' }}>
                    <mesh name="TeaPotBody001_0" geometry={nodes.TeaPotBody001_0.geometry} material={materials.Black} userData={{ name: 'TeaPotBody.001_0' }} />
                  </group>
                  <group name="TeaPotHandle001" position={[0.19, -1.26, 0.85]} rotation={[-Math.PI / 2, -Math.PI / 8, Math.PI / 2]} userData={{ name: 'TeaPotHandle.001' }}>
                    <mesh name="TeaPotHandle001_0" geometry={nodes.TeaPotHandle001_0.geometry} material={materials.TeaPotWhite} userData={{ name: 'TeaPotHandle.001_0' }} />
                  </group>
                </group>
              </group>
              <group name="TableStand" position={[0, 0, 1]} scale={[0.5, 0.5, 1]} userData={{ name: 'TableStand' }}>
                <mesh name="TableStand_0" geometry={nodes.TableStand_0.geometry} material={materials.WoodDark} userData={{ name: 'TableStand_0' }} />
              </group>
              <group name="TableTop" position={[0, 0, 2]} scale={[1.8, 1.8, 0.12]} userData={{ name: 'TableTop' }}>
                <mesh name="TableTop_0" geometry={nodes.TableTop_0.geometry} material={materials.WoodDark} userData={{ name: 'TableTop_0' }} />
              </group>
            </group>
            <group name="Walls" userData={{ name: 'Walls' }}>
              <group name="Windows" position={[1.9, -4, 1]} scale={[0.45, 2, 0.57]} userData={{ name: 'Windows' }}>
                <mesh name="Windows_0" geometry={nodes.Windows_0.geometry} material={materials.Wood} userData={{ name: 'Windows_0' }} />
                <mesh name="Windows_1" geometry={nodes.Windows_1.geometry} material={materials.WindowWhite} userData={{ name: 'Windows_1' }} />
              </group>
              <group name="LowCeil" position={[-2, -3, 7]} userData={{ name: 'LowCeil' }}>
                <group name="WallLeft" position={[2, -1, -3]} rotation={[-Math.PI / 2, 0, -Math.PI]} userData={{ name: 'WallLeft' }}>
                  <mesh name="WallLeft_0" geometry={nodes.WallLeft_0.geometry} material={materials.TatamiGreen} userData={{ name: 'WallLeft_0' }} />
                  <mesh name="WallLeft_1" geometry={nodes.WallLeft_1.geometry} material={materials.Wood} userData={{ name: 'WallLeft_1' }} />
                </group>
                <mesh name="LowCeil_0" geometry={nodes.LowCeil_0.geometry} material={materials.Wood} userData={{ name: 'LowCeil_0' }} />
              </group>
              <group name="WallRight" position={[-4, 0, 4]} rotation={[Math.PI / 2, Math.PI / 2, 0]} userData={{ name: 'WallRight' }}>
                <mesh name="WallRight_0" geometry={nodes.WallRight_0.geometry} material={materials.TatamiGreen} userData={{ name: 'WallRight_0' }} />
                <mesh name="WallRight_1" geometry={nodes.WallRight_1.geometry} material={materials.WallLight} userData={{ name: 'WallRight_1' }} />
              </group>
              <group name="Floor" userData={{ name: 'Floor' }}>
                <mesh name="Floor_0" geometry={nodes.Floor_0.geometry} material={materials.TatamiGreen} userData={{ name: 'Floor_0' }} />
                <mesh name="Floor_1" geometry={nodes.Floor_1.geometry} material={materials.Wood} userData={{ name: 'Floor_1' }} />
                <mesh name="Floor_2" geometry={nodes.Floor_2.geometry} material={materials.FloorWhite} userData={{ name: 'Floor_2' }} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room12-transformed.glb')
